      - name: Mirror Repo to Public Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add mirror https://github.com/arias1993/practica-7-insercion-audio-video.git
          git push --force mirror main

      - name: Enable GitHub Pages
        run: |
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/arias1993/practica-7-insercion-audio-video/pages \
               -d '{"source":{"branch":"main"}}'
